version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: myscaper_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myscaper_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: myscaper_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Set your email here
      PGADMIN_DEFAULT_PASSWORD: admin # Set your password here
    ports:
      - "8080:80" # Expose pgAdmin on port 8080

volumes:
  postgres_data:
